### ISSUE TITLE
Migrate site to deno deploy

### ISSUE THREAD

**Issue by hasanhaja** [hasanhaja/astro-webcv#22]
# Todo
- [x] Add the Astro deno deploy integration
- [ ] Add deno deploy GitHub Actions script
- [ ] Remove references to Vercel hosting
- [ ] Add pnpm to GitHub actions
